  name: Test arm64 failure

  on:
    pull_request:
      branches:
        - '**'  # Matches all branch names, for PRs
    push:
      branches:
        - 'main'  # Run tests on main branch

  jobs:
    pytest:
      name: pytest
      runs-on: ${{ matrix.os }}
      timeout-minutes: 5
      strategy:
        matrix:
          os: [ubuntu-latest, ubuntu-24.04-arm]
        fail-fast: False
      steps:
        - uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            version: "0.6.7"
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version-file: "pyproject.toml"

        - name: Install the project
          run: uvx --python-preference only-managed --no-cache -v uv@0.6.5 pip install faster-fifo

        - name: Run python and import faster_fifo
          run: |
            PYTHON_JIT=1 uvx --python-preference only-managed --no-cache -v --with faster_fifo python -c "import faster_fifo; print(faster_fifo.Queue)"